obj-$(CONFIG_DEMO_DEVICE_CORE)   += core.o
obj-$(CONFIG_DEMO_DEVICE_CORE)   += device.o
obj-$(CONFIG_DEMO_DEVICE_CORE)   += bus.o
obj-$(CONFIG_DEMO_DEVICE_CORE)   += class.o
obj-$(CONFIG_DEMO_DEVICE_CORE)   += driver.o
obj-$(CONFIG_DEMO_DEVICE_CORE)   += devres.o
