obj-$(CONFIG_DEMO_CODE_HLIST) += hlist_demo.o
obj-$(CONFIG_DEMO_DEBUGFS)    += demo_debugfs.o
obj-$(CONFIG_DEMO_PROCFS)     += demo_procfs.o
obj-$(CONFIG_DEMO_FILESYSTEM) += demo_filesystem.o
obj-$(CONFIG_DEMO_BUS)        += demo_bus.o
obj-$(CONFIG_DEMO_BUS_DEV)    += demo_bus_device.o
obj-$(CONFIG_DEMO_KOBJECT)    += demo_kobject.o
obj-$(CONFIG_DEMO_DEVICE_CORE) += device/
